### ISSUE TITLE
Something broke a bunch of tests

### ISSUE THREAD

**Issue by ralsina** [getnikola/plugins#103]
Probably the plugin initialization refactor.

```
>       for p in self.plugin_manager.getPluginsOfCategory('PostScanner'):
E       AttributeError: 'Nikola' object has no attribute 'plugin_manager'
```

**Comment by Kwpolska** [comment]
I tried to [fix that](https://travis-ci.org/getnikola/plugins/jobs/76677451) on master 2 days ago, and apparently more bugs appeared, this time in plugins I have no idea how they work.

**Comment by ralsina** [comment]
Don't worry I got this.

**Comment by ralsina** [comment]
@Kwpolska I was pushing the exact same fix you did :-)
