### ISSUE TITLE
Snippets plugin

### ISSUE THREAD

**Issue by humitos** [getnikola/plugins#122]
Hello,

I'm thinking on a `snippets` plugins, a directive for .rst that receive some attributes and replace them in a HTML template. Something like:

```
.. snippet:: bootstrap-button
   :id: donate-button
   :class: btn btn-lg btn-primary
   :href: /en/donations/payment-methods

   Donate
```

And, the plugin should have a folder containing all the HTML templates with some placeholders. In this case, it should have a `bootstrap-button.html` with this on it:

```
   <div style="text-align: center; margin-top: 25px; margin-bottom: 25px;">
     <a class="${class}" href="${href}">
       ${content}
     </a>
   </div>
```

What do you think? Is it a good idea? Do you have a better idea to implement this?

**Comment by ralsina** [comment]
Sounds like a good idea!

I am not sure you can have  a directive with arbitrary options tho.

**Comment by Aeyoun** [comment]
I’ve been thinking about the same thing today. Except, I didn’t see the use-cases for options.

But I’d want it to be a Nikola feature and not a RST/Markdown extension. ;)

Were thinking of something like, `<!-- FRAGMENT:sign-up-form.md -->`.

**Comment by humitos** [comment]
@Aeyoun a Nikola feature? How? Could you explain a little bit more about this?

You mean, something like a `.. include::` directive with some attributes/context to pass to it?

**Comment by humitos** [comment]
Here it is the PR for this issue: https://github.com/getnikola/plugins/pull/126

I used `.. template::` as directive because I didn't remember this issue :P

**Comment by ralsina** [comment]
So, this is templated shortcodes, more or less. Closing.

**Comment by denibertovic** [comment]
@ralsina what would be the canonical way to include snippets at end of each post if the posts are markdown?

**Comment by ralsina** [comment]
I don't have the context of what was happening in a conversation from 2016
:-)

**Comment by denibertovic** [comment]
@ralsina I apologize I should have been more clear...Perhaps I should have opened a new issue but this seemed related. Anyway, I want to be able to embed a snippet (doesn't have to be templated it can be just hardcoded snippet of text/markdown) at the end of _some_ posts so I don't have to copy paste every time. Is that possible while using markdown to write the posts?

**Comment by Kwpolska** [comment]
For my blog, I have a sort-of-snippet at the end of posts (appears in the HTML page only), done via templates: https://github.com/Kwpolska/chriswarrick.com/blob/0af7365f904f8f7cc0c0419a23cface923c0d819/themes/kw/templates/post.tmpl#L34

**Comment by ralsina** [comment]
If it's always the same text?

Throw it in, say, "shortcodes/whatever.tmpl" and put this in your markdown:

{{% whatever %}}

**Comment by denibertovic** [comment]
@Kwpolska  This seems like an interesting approach. I assume I can have different tags for different snippets then.

@ralsina  It's the same text yes. Hmm do I have to enable shortcodes somehow in the config? Cause `{{% whatever %}}` just shows up like that .... it doesn't get templated out with the text that's in the actual .tmpl file.

**Comment by ralsina** [comment]
https://asciinema.org/a/HPPersdIddTGdZwpF1oMw90SX

**Comment by denibertovic** [comment]
Thanks @ralsina for your help. I had to upgrade my version of Nikola. :)
