### ISSUE TITLE
localsearch links are relative to domain root

### ISSUE THREAD

**Issue by tritium21** [getnikola/plugins#140]
if your SITE_URL is, for example "http://some.domain/~someuser/", and you have a post at "http://some.domain/~someuser/posts/mypost.html", localsearch will record the location of the post as "/posts/mypost.html", not the correct "/~someuser/posts/mypost.html" (or the full URL, for that matter).

Simple fix, on line 84 of ``localsearch/__init__.py``, just add the keyword argument absolute=True to the call to the permalink method.

**Comment by Kwpolska** [comment]
I’m just going to apply that fix and hope it works. Thanks!
