### ISSUE TITLE
localsearch: index link at domain root while Nikola is deployed to a subdirectory

### ISSUE THREAD

**Issue by davidak** [getnikola/plugins#144]
example:

the site is at https://davidak.basecom.de/webseite-2016/

`SITE_URL = "https://davidak.basecom.de/webseite-2016/"`

but in the source, the search index is at https://davidak.basecom.de/assets/js/tipuesearch_set.js?_=1457303077220

it is not critical for me since it is a staging system, but maybe someone want to use it this way.

**Comment by ralsina** [comment]
Ok, so apparently, is that the plugin does this:

```
data["url"] = post.permalink(lang, absolute=True)
```

I wonder why that is not producing the right URL, though.

**Comment by davidak** [comment]
i don't think it is this code. it seams to generates URLs of results.

what i mean here is the location of the index.

you can see it right now at https://davidak.basecom.de/webseite-2016/ in the JS console...

**Comment by ralsina** [comment]
Doesn't that come from the conf.py.sample? Those always should be adjusted
to your configuration.

**Comment by davidak** [comment]
ah, now i understand what you mean.

yes, you are right.

https://github.com/getnikola/plugins/blob/672e7b5b8d7ca66c873befbcc888eea3c6611c41/v7/localsearch/conf.py.sample#L41
