### ISSUE TITLE
Shortcode name conflicts with rest_html5 plugin

### ISSUE THREAD

**Issue by andredias** [getnikola/plugins#147]
I'm using rest_html5 plugin but I can't use the `chart directive` because there are some conflicts with Shortcode names.

Steps to reproduce:

1. `nikola init --demo demo`
2. `cd demo`
3. `nikola plugin -i rest_html5`
4. Include conf.py.sample contents in conf.py
5. `nikola build`

Error messages:
[2016-05-22T21:01:30Z] WARNING: Nikola: Shortcode name conflict: media
[2016-05-22T21:01:30Z] WARNING: Nikola: Shortcode name conflict: post-list
[2016-05-22T21:01:30Z] WARNING: Nikola: Shortcode name conflict: chart

Is there a workaround?

**Comment by ralsina** [comment]
This seems to be caused by a few plugins being loaded twice. It should be harmless, but I will try to find a workaround.

**Comment by ralsina** [comment]
So, the problem is that both rest and rest_html5 plugin try to enable all the RestExtension plugins.

There are a few workarounds, I'll get one in there.

**Comment by andredias** [comment]
Hi, there.

When will this fix be released?

**Comment by Kwpolska** [comment]
Done, updated the plugin site too.
