### ISSUE TITLE
ReST plugin strips single title

### ISSUE THREAD

**Issue by felixfontein** [getnikola/plugins#153]
I've noticed that if I have a .rst post which has one header, that one will be removed from the output. So if I have two pages:

Page 1:
```
Test
====

This is a test.
```

Page 2:
```
Test
====

This is a test.

Test2
=====

This is another test.
```

Then I would expect that Page 1 looks like Page 2 with the second section removed, but it ends up being just "This is a test." for Page 1 with the section header removed. I don't know why this is the default behavior, but I noticed it can be changed by modifying the ReST plugin by replacing
``` .py
return pub.writer.parts['docinfo'] + pub.writer.parts['fragment'], pub.document.reporter.max_level, pub.settings.record_dependencies
```
with
``` .py
return pub.writer.parts['html_title'] + pub.writer.parts['docinfo'] + pub.writer.parts['fragment'], pub.document.reporter.max_level, pub.settings.record_dependencies
```
at the end of `rst2html`.

I guess changing the default is not a good idea, but would it be acceptable to add an option to force inclusion of the HTML title?

**Comment by Kwpolska** [comment]
Mind reporting this in the main repo (getnikola/nikola) instead and closing this?

**Comment by felixfontein** [comment]
Whoops. I thought I was there... :)
