### ISSUE TITLE
upgrade_metadata lacks README

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [getnikola/plugins#154]
There is currently no indication on what upgrade_metadata does, what options can be set in conf.py, or anything else for that matter. Would someone be kind enough to write a README? Else, can it be integrated into core and removed from the plugins directory?

**Comment by tritium21** [comment]
getnikola/nikola#1692
getnikola/nikola#1689

**Comment by Kwpolska** [comment]
Added `README.md`:

> This is a plugin to upgrade metadata in `.meta` files from the old format (without descriptions) to the new reST-esque format. It only applies to users with two-file posts (`.meta` files alongside text) in the older format (up to 7 lines of text without any descriptions), used by Nikola before v7.0.0. If you need to use this plugin, **you will be warned** by `nikola build` — otherwise, there is no need to install it.
