### ISSUE TITLE
Generic compile extension plugin

### ISSUE THREAD

**Issue by atiro** [getnikola/plugins#164]
I'd like to add https://hypothes.is support to all pages on my site. It's a trivial addition of a JS include in the header, which I thought I would do cleanly by adding it as a plugin. However, short of hacking in:

site.template_hooks['extra_head'].append('<script async defer src="//hypothes.is/embed.js"></script>')

directly into the markdown plugin, I can't identify how I can add it as a standalone plugin that it will run as part of the normal build. Is this possible ?

**Comment by Kwpolska** [comment]
IMO, this is not clean. There are better ways:

1. Just add it to your conf.py file, which is the easiest way for a single line.
2. Add it to your base.tmpl/base_helper.tmpl, which makes the most sense if you have a custom template.
3. If you must, create a ConfigPlugin that uses template hooks. But the first two ideas are much simpler.
