### ISSUE TITLE
[orgmode] Pygments is highlighting html from org-html-format-code

### ISSUE THREAD

**Issue by sesamemucho** [getnikola/plugins#165]
At least from cpp and python code blocks, Pygments is highlighting html from org-html-format-code instead of the source code. For instance, the source code block

> # +BEGIN_SRC cpp ::exports code
> 
> int
> c = 2;
> for( int i = 0; i < 42; i++ ) {
>     c += i;
> }
> # +END_SRC

is highlighted as 

> <div class="highlight"><pre><span></span><span class="o">&lt;</span><span class="n">span</span> <span class="n">style</span><span class="o">=</span><span class="s">"font-weight: bold; text-decoration: underline;"</span><span class="o">&gt;</span><span class="kt">int</span><span class="o">&lt;/</span><span class="n">span</span><span class="o">&gt;</span> <span class="o">&lt;</span><span class="n">span</span> <span class="n">style</span><span class="o">=</span><span class="s">"font-weight: bold; font-style: italic;"</span><span class="o">&gt;</span><span class="n">c</span><span class="o">&lt;/</span><span class="n">span</span><span class="o">&gt;</span> <span class="o">=</span> <span class="mi">2</span><span class="p">;</span>
> <span class="o">&lt;</span><span class="n">span</span> <span class="n">style</span><span class="o">=</span><span class="s">"font-weight: bold;"</span><span class="o">&gt;</span><span class="k">for</span><span class="o">&lt;/</span><span class="n">span</span><span class="o">&gt;</span><span class="p">(</span> <span class="o">&lt;</span><span class="n">span</span> <span class="n">style</span><span class="o">=</span><span class="s">"font-weight: bold; text-decoration: underline;"</span><span class="o">&gt;</span><span class="kt">int</span><span class="o">&lt;/</span><span class="n">span</span><span class="o">&gt;</span> <span class="o">&lt;</span><span class="n">span</span> <span class="n">style</span><span class="o">=</span><span class="s">"font-weight: bold; font-style: italic;"</span><span class="o">&gt;</span><span class="n">i</span><span class="o">&lt;/</span><span class="n">span</span><span class="o">&gt;</span> <span class="o">=</span> <span class="mi">0</span><span class="p">;</span> <span class="n">i</span> <span class="o">&lt;</span> <span class="mi">42</span><span class="p">;</span> <span class="n">i</span><span class="o">++</span> <span class="p">)</span> <span class="p">{</span>
>     <span class="n">c</span> <span class="o">+=</span> <span class="n">i</span><span class="p">;</span>
> <span class="p">}</span>
> </pre></div>

I can fix it my removing org-html-format-code from org-html-src-block in init.el:

>    (let\* ((lang (org-element-property :language src-block))
>           (code-info (org-export-unravel-code element))
>           (code (car code-info))
>           ;;(code (org-html-format-code src-block info))
>          )

and I get the correct highlighting:

> <div class="highlight"><pre><span></span><span class="kt">int</span> <span class="n">c</span> <span class="o">=</span> <span class="mi">2</span><span class="p">;</span>
> <span class="k">for</span><span class="p">(</span> <span class="kt">int</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span><span class="p">;</span> <span class="n">i</span> <span class="o">&lt;</span> <span class="mi">42</span><span class="p">;</span> <span class="n">i</span><span class="o">++</span> <span class="p">)</span> <span class="p">{</span>
>     <span class="n">c</span> <span class="o">+=</span> <span class="n">i</span><span class="p">;</span>
> <span class="p">}</span>
> </pre></div>

But, I wonder if I'm missing some configuration setting? I'm using emacs 25.1.50.1 and org-mode 8.3.5.

Thanks

**Comment by punchagan** [comment]
Can you try dropping the `-g` flag to pygments as mentioned here: https://github.com/getnikola/plugins/issues/162 ?

**Comment by sesamemucho** [comment]
No, no luck there. The input to Pygments has already been converted to html, and Pygments is trying to highlight that.

**Comment by punchagan** [comment]
What version of org-mode are you using?  I'm unable to reproduce this with 8.3.x or 9.0.  Please update to a relatively recent version of org-mode and feel free to re-open this if the problem persists.
