### ISSUE TITLE
[orgmode] "htmlize.el >= 1.34 required" can be a bogus error

### ISSUE THREAD

**Issue by ncouture** [getnikola/plugins#171]
When building a nikola resource with the orgmode plugin I am seeing with what seems to be an error:

```
Cannot fontify src block (htmlize.el >= 1.34 required)
```

This does not prevent the build process to complete -- version of htmlize used is 1.47.

**Comment by ermanno** [comment]
Do the source code blocks appear fontified and colorized correctly? Because in my case, I encounter the error *and* the generated file does not show colorized and fontified source code.
