### ISSUE TITLE
Plugin development: add API to add additional css styles?

### ISSUE THREAD

**Issue by xuhdev** [getnikola/plugins#174]
Currently, per my understanding, a plugin can only add new css styles through template hooks. However, if a hook is used, a user cannot customize through `custom.css`, 'cause `custom.css` is used before the hook. What do you think?

**Comment by Kwpolska** [comment]
I think your plugins should just say “please add this CSS” in install instructions instead of messing with template hooks..

**Comment by ralsina** [comment]
Agreed.
