### ISSUE TITLE
[publication_list] Plugin needs to be adjusted to current Nikola master

### ISSUE THREAD

**Issue by felixfontein** [getnikola/plugins#180]
The combination of this plugin and getnikola/nikola#2532 breaks the tests: https://travis-ci.org/getnikola/plugins/jobs/167842014

**Comment by xuhdev** [comment]
I don't understand, why would getnikola/nikola#2532 break dependency tests? They seem totally irrelevant...

**Comment by xuhdev** [comment]
Removing the line `self.deps = 'tests/data/publication_list/test.bib'` in the test file "fixes" the test, but there might be something wrong...

**Comment by Kwpolska** [comment]
There is, the test doesn’t really test it. I’m working on it.

**Comment by felixfontein** [comment]
The test uses the ReST compiler, which now bails out if it doesn't gets a `Post` object passed. Before getnikola/nikola#2532, it would try to find out the post object by itself.

@Kwpolska: how about adjusting the ReST compiler such that the `compile_html` method tries to find the `Post` object by itself (as it did before)? This should reduce breakages like this one.

**Comment by Kwpolska** [comment]
That still won’t cut it:
```
<div class="system-message">
<p class="system-message-title">System Message: ERROR/3 (<tt class="docutils">&lt;string&gt;</tt>, line 1)</p>
<p>Unknown directive type &quot;publication_list&quot;.</p>
<pre class="literal-block">
.. publication_list:: tests/data/publication_list/test.bib
        :highlight_author: Nikola Tesla
</pre>
</div>
 3 DependencyList(None, [])
```

**Comment by Kwpolska** [comment]
Wait, I’m missing dependencies locally. It’s a one-line fix then.

**Comment by Kwpolska** [comment]
> @Kwpolska: how about adjusting the ReST compiler such that the compile_html method tries to find the Post object by itself (as it did before)? This should reduce breakages like this one.

I had to [patch `test_rst_compiler.py`](https://github.com/getnikola/plugins/commit/0225f88cfa0f7a6374f79bb45c2d4a4aa2e4950d) to make that finding work.

**Comment by felixfontein** [comment]
Ok. Main thing is that it's fixed now :)
