### ISSUE TITLE
[orgmode] TEASER_END not working

### ISSUE THREAD

**Issue by Allaman** [getnikola/plugins#186]
Hello,

I have an issue with orgmode and teasers not showing in my index file. To verify my configuration I tried a markdown post and teaser is working fine there.

What I tried so far in my org file:
`#+RST: .. TEASER_END`

and 
```
#+BEGIN_COMMENT
.. TEASER_END
#+END_COMMENT
```
- nikola 7.8.1
- orgmode plugin installed with `nikola plugin -i orgmode`

Is there something I do not understand?
Thanks

**Comment by Kwpolska** [comment]
I’m a Vim person myself, but org-mode docs say:

```
#+HTML: <!-- TEASER_END -->
```

**Comment by Allaman** [comment]
@Kwpolska Incredible how easy this works, never would have thought about this option, I don't know why... Thank you very much
