### ISSUE TITLE
Plugin sphinx_roles and rest_html5 don't work together

### ISSUE THREAD

**Issue by micheal** [getnikola/plugins#190]
I'm trying to move to HTML5 output, but I make use of the sphinx_roles plugin. When I leave the compiler on 'rest', sphinx_roles works just fine. When I move the 'rest_html5', sphinx breaks.

I thought it might be this line in the sphinx plugin:

~~~
from nikola.plugins.compile.rest import add_node
~~~

and I changed it to:

~~~
from nikola.plugins.rest_html5.rest_html5 import add_node
~~~

However, that didn't work either. I'd like to make use of both of these plugins.

**Comment by ralsina** [comment]
"didn't work" how? Can you post error messages?

**Comment by Kwpolska** [comment]
You need to have the built-in reST compiler enabled and set for an extension for reST plugins to work. Please make sure `rest` is in your COMPILERS and POSTS/PAGES lists.

**Comment by micheal** [comment]
So there's no way to utilize the rest_html5 parser with plugins? I don't want the html4 parser, that's why I removed it from my COMPILERS list.

**Comment by Kwpolska** [comment]
You **can** use rest_html5 with the plugins. Just do [this](https://github.com/getnikola/plugins/blob/master/v7/rest_html5/conf.py.sample):

```py
COMPILERS = {
    'rest': ('.rst4',),
    'rest_html5': ('.rst', '.txt'),
}

POSTS = (
    ("posts/*.rst4", "posts", "post.tmpl"),
    ("posts/*.rst", "posts", "post.tmpl"),
    ("posts/*.txt", "posts", "post.tmpl"),
)

# NOTE: if you want to use the Nikola-provided reST extensions, you need to
#       keep the original `rest` compiler in COMPILERS *and* POSTS/PAGES,
#       otherwise they will not get loaded.
```

**Comment by micheal** [comment]
Unfortunately that doesn't work. I get the error:

~~~
:kbd:`cmd`
System Message: ERROR/3 (<string> line 38)
~~~

rst-test.rst:

~~~
Testing Grounds
===============

:kbd:`cmd`
~~~

conf.py:

~~~
POSTS = (
	('posts/*.rst', 'blog', 'post.tmpl'),
	('posts/*.md', 'blog', 'post.tmpl'),
	('posts/*.oldrst', 'blog', 'post.tmpl'),
)

PAGES = (
	('pages/*.rst', '', 'story.tmpl'),
	('pages/*.md', '', 'story.tmpl'),
	('pages/*.oldrst', '', 'story.tmpl'),

	('projects/*.rst', 'projects', 'project.tmpl'),
	('projects/*.oldrst', 'projects', 'project.tmpl'),
)

COMPILERS = {
	'rest': ('.oldrst'),
	'rest_html5': ('.rst', '.txt'),
	'markdown': ('.md', '.mdown', '.markdown'),
	'html': ('.html',),
}
~~~

I have cleared the build folder and cache folder and still get that error.

**Comment by micheal** [comment]
I was missing a comma at the end. Thanks.
