### ISSUE TITLE
[import_goodreads] No documentation

### ISSUE THREAD

**Issue by Patterner** [getnikola/plugins#207]
I have no idea how to use that plugin.

**Comment by Patterner** [comment]
```
> nikola help
...
nikola import_goodreads     import a Goodreads RSS
...

> nikola import_goodreads
ERROR: Nikola: Unknown command import_goodreads
```

**Comment by felixfontein** [comment]
I get:
```
> nikola import_goodreads
Purpose: import a Goodreads RSS
Usage:   nikola import_goodreads [options] rss_url

Options:
  -o ARG, --output-folder=ARG  Location to write imported content.
```
It looks like there's a problem with your nikola and/or plugin installation. Which python version and nikola version are you using?

**Comment by Patterner** [comment]
Python 3.6.0 and Nikola v7.8.3.  the virtualenv was setup yesterday, the site files are older.

**Comment by felixfontein** [comment]
Hmm, here it works fine (Python 3.6.0, Nikola github master which is essentially v7.8.3, though without virtualenv). I created an empty site with `nikola init -qd`, entered the folder, imported the plugin and got the help text.

Can you try to reproduce this with an empty site? Like:
```
nikola init -qd test
cd test
nikola plugin -i import_goodreads
nikola import_goodreads
```

**Comment by Patterner** [comment]
That works. But I found the problem: it doesn't work if the current directory is `plugins`. The site's root works.
