### ISSUE TITLE
[material-theme] Missing `front_index_header`

### ISSUE THREAD

**Issue by henryiii** [getnikola/plugins#209]
This theme is missing the `FRONT_INDEX_HEADER` html insertion. It can be added by inserting:

```
    {% if 'main_index' in pagekind %}
    {{ front_index_header }}
    {% endif %}
```

Just after
```
{% block content %}
    <div class="postindex well post-material ">
```
in `index.tmpl`. (Guessed by comparing with the default theme, seems to work fine)

**Comment by Kwpolska** [comment]
Do you want to make a pull request for this?

**Comment by ralsina** [comment]
So this seems fixed,
