### ISSUE TITLE
[emoji] tortue.me site seems to be gone

### ISSUE THREAD

**Issue by gour** [getnikola/plugins#211]
Hello,

It seems that the [site](http://tortue.me) which was hosting emoji images is gone...Any alternatives?

**Comment by Kwpolska** [comment]
You could try [using GitHub’s resources](https://developer.github.com/v3/emojis/), finding someone else who rehosts those emojis, or using real Unicode characters instead. (PRs welcome if you find a good host)

**Comment by ralsina** [comment]
I found it in a CDN so there it is.
