### ISSUE TITLE
[pkgindex_compiler] Updated conf.py.sample files are not updated on plugin site rebuild

### ISSUE THREAD

**Issue by felixfontein** [getnikola/plugins#221]
Compare https://plugins.getnikola.com/v7/hierarchical_pages/ vs. https://github.com/getnikola/plugins/blob/master/v7/hierarchical_pages/conf.py.sample (I assume you didn't updated the MarkDown by hand...)

**Comment by Kwpolska** [comment]
I actually did, but yes, dependencies seem to be broken/missing.

**Comment by felixfontein** [comment]
This should be fixable with calling `post.add_dependency(path_to_conf_py_sample, add='fragment')` in `CompilePackageIndexEntries.read_metadata` in case `conf.py.sample` exists.

**Comment by felixfontein** [comment]
I guess similar dependencies should be added on the `.plugin` file, and on all the `requirements*.txt` files.

Hmm, maybe it is better to add the whole `metadata` object as an uptodate dependency?

**Comment by Kwpolska** [comment]
I always thought post metadata **were** dependencies, and perhaps this is why I didn’t bother doing any dependency stuff… Was anything ever changed in that regard? What happens with two-file posts?

**Comment by Kwpolska** [comment]
(In any case, I’ve got a patch ready for `pkgindex_compiler`)

**Comment by felixfontein** [comment]
The post source file and the `.meta` file (for two-file posts) are file dependencies. That doesn't work for metadata coming from other sources, though, like in this case.
