### ISSUE TITLE
Allow README.rst? 

### ISSUE THREAD

**Issue by felixfontein** [getnikola/plugins#225]
Since the new page renders the README.md to HTML with Nikola, why not allow other formats for plugin README files, in particular Restructured Text? Github also renders README.rst files.

**Comment by Kwpolska** [comment]
Is it really necessary? 84% of our plugins’ README files are below 200 words. The remaining ones usually contain code samples or extensive usage documentation. The largest ones are: `latex` with 1018 words (and a ton of LaTeX support details), `windows_live_tiles` with 562 words (complex behavior), `static_comments` (540; config) and `projectpages` (538; long usage documentation)

But then there are plugins with really short documentation, that could be happily live as unformatted text. (Half of them are 70 words or less. This comment is **108** words long.)

Sure, there are no technical obstacles, but Nikola itself suffers from too many options already — let’s not overcomplicate this plugins index.

**Comment by felixfontein** [comment]
I just prefer writing ReST over MarkDown. But fine with me.
