### ISSUE TITLE
[orgmode]

### ISSUE THREAD

**Issue by mpslxz** [getnikola/plugins#227]
The plugin does not compile images of the org file into the html.

**Comment by Kwpolska** [comment]
Please be more clear. What do you mean? What is the input, what is the output?

**Comment by mpslxz** [comment]
If I include an image in an org file ([[path_to_the_file]]), it does not get exported with the html.

**Comment by Kwpolska** [comment]
Please show the **exact** input file that fails, and the corresponding .html file in `cache/`.

**Comment by mpslxz** [comment]
The html in cache does have the image. But when it is served all together, it looks like this:
![screen shot](https://cloud.githubusercontent.com/assets/7834847/25987160/94710a9c-36a7-11e7-9f41-98e89c2f0d03.png)

Org post:
``` #+BEGIN_COMMENT
.. title: test
.. slug: test
.. date: 2017-05-11 00:56:31 UTC-07:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT


* This is a picture:
[[~/one.jpg]]
```

**Comment by Kwpolska** [comment]
You can’t refer to an image like this. You must refer to it as `/images/one.jpg` and place the image in the `images/` folder of your site. Nikola won’t copy any files you don’t put in a recognized directory in the site (`images/` or `files/` by default).

See also: #188.

**Comment by mpslxz** [comment]
Oh I see. You are absolutely right. Thanks for explanation.
