### ISSUE TITLE
What to do with v8-only plugins

### ISSUE THREAD

**Issue by felixfontein** [getnikola/plugins#237]
When getnikola/nikola#2856 is merged, I want to use the added functions to improve the `static_comments` plugin (#232). But the plugin will then depend on nikola master, which is the new development trunk for v8.

Would it make sense to start a `/v8/` folder in the plugins repository for this, and put the new version only in there? (And keep the old version in `/v7/`?) Or how should this be organized?

**Comment by ralsina** [comment]
You can just set a minimum version on the plugin metadata. Of course there
is the problem of having two versions of the same plugin with different
supported versions :-)

I'd say give it the same name, put it in v8/ and use the metadata to
indicate version compatibility. Then we need to check if nikola theme -i
does "the right thing" and if it doesn't, make it do it.

**Comment by Kwpolska** [comment]
The same way we did before: `v7` has all current plugins that are compatible with v7 and v8. `v8` has v8-only plugins.

Make sure to ping me if the plugin lands, because the plugins site might not be compatible with all this as of now (it was back in the JS SPA days, I haven’t tested the new site for that yet)

**Comment by felixfontein** [comment]
I'll probably wait to see how getnikola/nikola#2830 evolves, so probably no PR for this in the near future.

I guess we should leave this issue open until the first plugin is in `/v8/`, otherwise someone else might ask this again.

**Comment by Kwpolska** [comment]
I added the first plugin, `v8/helloworld` (with the same code as `v7/helloworld`) in 7e5caac — so this can be closed.
