### ISSUE TITLE
[localsearch]: Works only for nikola within the root context

### ISSUE THREAD

**Issue by uli-heller** [getnikola/plugins#242]
* OK: SITE_URL="http://my-server.com/"
* KO: SITE_URL="http://my-server.com/nikola/"

**Comment by uli-heller** [comment]
For me, these changes to config.py work even for the 2nd SITE_URL:

```
...
# localsearch
SEARCH_FORM = """
    <span class="navbar-form navbar-left">
    <input type="text" id="tipue_search_input" class="form-control" placeholder="Search">
    </span>
"""
...
EXTRA_HEAD_DATA = ""
# localsearch
EXTRA_HEAD_DATA += """
    <link rel="stylesheet" type="text/css" href="/assets/css/tipuesearch.css">
"""
...
BODY_END = ""

# localsearch
BODY_END += """
    <!-- Modal -->
    <div id="search-results" class="modal fade" role="dialog" style="height: 80%;">
      <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Search Results:</h4>
          </div>
          <div class="modal-body" id="tipue_search_content" style="max-height: 600px; overflow-y: auto;">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <script>
"""
BODY_END += """
    var siteUrl = "{siteUrl}"
""".format(siteUrl = SITE_URL)
BODY_END += """
    $(document).ready(function() {
        $.when(
            $.getScript( siteUrl + "/assets/js/tipuesearch_set.js" ),
            $.getScript( siteUrl + "/assets/js/tipuesearch.js" ),
            $.Deferred(function( deferred ){
                $( deferred.resolve );
            })
        ).done(function() {
            $('#tipue_search_input').tipuesearch({
                'mode': 'json',
                'contentLocation': siteUrl + '/assets/js/tipuesearch_content.json'
            });
            $('#tipue_search_input').keyup(function (e) {
                if (e.keyCode == 13) {
                    $('#search-results').modal()
                }
            });
        });
    });
    </script>
"""
```

**Comment by ralsina** [comment]
Cool, can you do a PR?

**Comment by uli-heller** [comment]
Yes,I will do so tomorrow.

Am 25. Juli 2017, um 21:51, schrieb Roberto Alsina <notifications@github.com>:

Cool, can you do a PR?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/getnikola/plugins","title":"getnikola/plugins","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/getnikola/plugins">https://github.com/getnikola/plugins</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ralsina in #242: Cool, can you do a PR?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/getnikola/plugins/issues/242#issuecomment-317852200">https://github.com/getnikola/plugins/issues/242#issuecomment-317852200</a>"}}}
