### ISSUE TITLE
[orgmode]

### ISSUE THREAD

**Issue by bamsumit** [getnikola/plugins#245]
Hi

I am trying to use orgmode compiler in nikola. I have both emacs 22.3 and orgmode 9.0.9 setup on windows 10. I have also tried changing the init.el file with the following

(add-to-list 'load-path "C:\Org\org-9.0.9\lisp")
(add-to-list 'load-path "C:\Org\org-9.0.9\contrib\lisp" t)

conf.py is already configured as well.
Still I cannot use 'nikola build'. I get the following error

[2017-08-14T10:49:25Z] ERROR: Nikola: In order to use the orgmode compiler, you must install the "emacs" and "org-mode" software.
[2017-08-14T10:49:25Z] ERROR: Nikola: Exiting due to missing dependencies.

Any help would be appreciated

Sumit

**Comment by punchagan** [comment]
- Is Emacs on your executable path? 
- Nikola uses it's own custom `init.el` when starting Emacs.  You will need to edit the `init.el` file in your `<site>/plugins/orgmode/` directory, and make the changes required to let Emacs find your org-mode installation.

**Comment by bamsumit** [comment]
Hi @punchagan 

Yes emacs is on my executable path. I am able to run it from cmd line.
I have added the following in the init.el file as well

(add-to-list 'load-path "C:\Org\org-9.0.9\lisp")
(add-to-list 'load-path "C:\Org\org-9.0.9\contrib\lisp" t)
(require 'org)

Thanks for your response.

Sumit

**Comment by punchagan** [comment]
Please edit the `init.el` file supplied by the `orgmode` Nikola plugin present in your site's plugin directory.  The Emacs used by this plugin doesn't care about your `init.el` in `~/.emacs.d`.

**Comment by bamsumit** [comment]
Hi @punchagan I have made the changes in `<site>/plugins/orgmode/init.el` as you mentioned before.

**Comment by MarcoHassan** [comment]
any development so far?

did you solve the problem @bamsumit?

**Comment by bamsumit** [comment]
Hi @punchagan , I couldn't find a solution. So I moved away from using org mode on Nikola altogether.

**Comment by blank-manash** [comment]
I'm also facing the same issue, any help is appreciated.
