### ISSUE TITLE
[similarity] No way to control the number of similar posts displayed

### ISSUE THREAD

**Issue by vkazanov** [getnikola/plugins#249]
Currently similarity should a fixed number of similar posts, for my blog about half of them are not really relevant. 

Is there a way to only display the more similar ones..? Or control the number of posts displayed?

**Comment by ralsina** [comment]
Sure, you can edit the code :-)

Just kidding, I'll add a setting.

**Comment by ralsina** [comment]
Done in 35a1a985080e64eefe0201267fe8a7859065fa59
