### ISSUE TITLE
[asciidoc] Confusing PAGES in conf.py

### ISSUE THREAD

**Issue by farleylai** [getnikola/plugins#253]
Why is it written as `PAGES = PAGES + (("stories/*.asc", "posts", "post.tmpl"),)` instead of `PAGES = PAGES + (("pages/*.asc", "pages", "page.tmpl"),)` as other entries?

Is it a typo or intentional?

**Comment by Kwpolska** [comment]
Copy-paste bug. Fixed, thanks for reporting.

(`stories` is correct though, as this was the former name for `pages` that was still in use up until recently)
