### ISSUE TITLE
[import_feed] error  in import feeds

### ISSUE THREAD

**Issue by AmiraliNull** [getnikola/plugins#256]
i can't import feed and get an error!  
[Error text](https://beepaste.io/view/GwuNlG)  

i can import from other feed but this url has problem in import
https://virgool.io/feed/@amiralii

this happened on:  
Nikola==7.8.11  
feedparser==5.2.1

**Comment by ralsina** [comment]
Looks like that feed has a "modified date" for all items but no published date, which is unusual. I can work around it.

**Comment by ralsina** [comment]
Fixed, you can get version 0.2.1 of the plugin later today, or just get the patch (it's very small)
