### ISSUE TITLE
[publication_list] list from mulitple bibtex files

### ISSUE THREAD

**Issue by bishesh** [getnikola/plugins#261]
Can we give more than one .bib files with the `publication_list` directive ?
I would like the plugin to be able to read the bibtex entries from mulitple files and create the pages.
Something like:
``.. publication_list:: person1-publcations.bib person2-publications.bib person3-publications.bib``

**Comment by xuhdev** [comment]
I think this can be done (in the plugin) by concatenating all bib files into a single temporary bib file and load that file. However, the issue is that, how do we tell you are specifying multiple bib files, or a single bib file with spaces?

**Comment by bishesh** [comment]
I'm currently creating a combined file. But I think it would be nice if this feature is in the plugin as it simplifies having this in github/gitlab hosted page where we don't need to run this command to create a combined .bib source file.

I do not know exactly how the directives work, but is it possible to use the syntax such that the directive looks for a tuple/list of filenames instead of a single filename ? 
Sth like: 
``.. publication_list:: (p1-pub.bib, p2-pub.bib, p3-pub.bib)`` ?

**Comment by xuhdev** [comment]
I don't know :(  @Kwpolska I would appreciate if you can give some suggestions.

**Comment by ralsina** [comment]
Use a comma separated list, not even need for parenthesis.

Unless people actually use commas in filenames, in which case use something else :-)

**Comment by xuhdev** [comment]
This should be fixed now (should be available for download within 24h). If you don't mind, may I add your website as a live example in the document?

**Comment by xuhdev** [comment]
And add a link to the plugin on your website if you like :-)

**Comment by bishesh** [comment]
Thanks. The website where I am using these features of multiple files is an organisational website that is not public yet. I will send you the link once it is publicly launched. 
I have a personal website where I use Nikola and this plugin too, so if it is any useful you can add it as an example (I'd be keen to use other features such as hierarchy, issue #262 ) on this website: 
https://bishesh.github.io/

For adding the link to th plugin on my/our websites, we'll be happy to do that. Is there a way to edit the footer "Powered by Nikola", to be sth like "Powered by Nikola, and publication_list" for the publications page ?

**Comment by xuhdev** [comment]
Thanks! You can do so by modifying `CONTENT_FOOTER` in your `conf.py` file. I will add a link to your website.

**Comment by xuhdev** [comment]
Actually the fix was incomplete (found another issue). Can you try the latest version?

**Comment by bishesh** [comment]
Yes, the latest version fixes this, thanks.
