### ISSUE TITLE
[orgmode]Error while highlighting: UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by huhuang03** [getnikola/plugins#266]
In my post.org file, there is a source block which have no-english character.
```
#+BEGIN_SRC shell
# 重进进入fastboot模式
adb reboot bootloader
# 查询bootloader状态（是否锁住）
fasboot oem get-bootinfo
#+END_SRC
```
So the parse error log:
```
*** Error while highlighting: UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-29: 
ordinal not in range(128) (file "/Users/myname/source/myblog.io/bin/../lib/python3.6/codecs.py", line 376, in write) 
*** If this is a bug you want to report, please rerun with -v.
````

**Comment by Kwpolska** [comment]
Are your locales set correctly (to something that supports UTF-8, that is installed on your system)?
Could you test the solutions [here](http://blog.zhengdong.me/2012/11/22/coding-system-in-shell-command/) or [here](https://stackoverflow.com/questions/1826070/how-can-i-set-the-encoding-of-shell-command-on-region-output)?

**Comment by huhuang03** [comment]
Add
```(setq default-process-coding-system '(utf-8 . utf-8))```
in my dot file, solved. 

Thank you very much!
