### ISSUE TITLE
[latex_formula_renderer]

### ISSUE THREAD

**Issue by bk322** [getnikola/plugins#276]
Does it support formula numbering and referencing numbered formula? For example sphinx supports `:label: eqX` and <code>:eq:`eqX`</code> http://www.sphinx-doc.org/en/master/ext/math.html#role-eq

**Comment by felixfontein** [comment]
No, it doesn't. Formula numbering is something the plugins using this plugin (it only provides infrastructure for other plugins, nothing you can directly use as an end-user!) must do themselves.
What I could do is add support to include a number/label in the rendered output. But the numbering must be done by the calling plugin.

**Comment by felixfontein** [comment]
@bk322: Does this answer your question? Do you need more information? Or are interested in having number/label support in the plugin?

**Comment by bk322** [comment]
@felixfontein yes, it answers my question. I'm interested in having number/label support for equations on the ReST level. You say it should not be implemented on the level of this plugin. I believe plugins which support the numbering does not exist yet. If you know some -- I'd be grateful for links.

**Comment by ralsina** [comment]
@bk322 I could add those roles as part of our sphinx compatibility plugins.

**Comment by ralsina** [comment]
@felixfontein 

* State between invocations of the same role in the same document is not a problem
* Label references are not a problem, worst case you end with a reference that points to something that doesn't exist.

I am going to take a shot during lunch right now.

**Comment by ralsina** [comment]
Done in 84ecbadb0807cb16e404764c0d113a8149bd2c1d

**Comment by ralsina** [comment]
Of course I have no idea what Sphinx actually **does** with that syntax but what my version does is:

* If you use a **label** option in a math block, the 1st equation in that block will have that id.
* If you use the **eq** role then it will create a link to that equation

**Comment by ralsina** [comment]
Closing since it seems nobody needs to do anything else?

**Comment by felixfontein** [comment]
@ralsina In Sphinx, the result is supposed to look like in these screenshots: https://github.com/sphinx-doc/sphinx/issues/2122#issuecomment-167396937 How does it look like in your code? I don't see where/how the number is generated or inserted.

**Comment by ralsina** [comment]
@felixfontein number is not visible, it just adds an anchor with whatever is put in :label: and :eq: creates a link to that.
