### ISSUE TITLE
[orgmode] Plugin is having issues with the new orgmode and emacs 26

### ISSUE THREAD

**Issue by mpslxz** [getnikola/plugins#281]
The orgmode plugin is not compatible with org v9.
The following error is shown:

> Scanning posts.....done!
.  render_posts:cache/pages/index.html
Cannot open load file: package
TaskError - taskid:render_posts:cache/pages/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/user/homepage/plugins/orgmode/orgmode.py", line 74, in compile
    subprocess.check_call(command)
  File "/home/user/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['emacs', '--batch', '-l', '/home/user/homepage/plugins/orgmode/init.el', '--eval', '(nikola-html-export "/home/user/homepage/pages/index.org" "/home/user/homepage/cache/pages/index.html")']' returned non-zero exit status 255.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/nikola/post.py", line 652, in compile
    lang)
  File "/home/user/homepage/plugins/orgmode/orgmode.py", line 94, in compile
    source, e.returncode))
Exception: Cannot compile pages/index.org -- bad org-mode configuration (return code 255)

**Comment by punchagan** [comment]
I'm unable to reproduce this on a `test` site with no configuration changes. 

You could try running this emacs batch command manually to see what the problem is

```sh
emacs --batch -l /home/user/homepage/plugins/orgmode/init.el --eval '(nikola-html-export "/home/user/homepage/pages/index.org" "/home/user/homepage/cache/pages/index.html")'
```

**Comment by mpslxz** [comment]
I found the issue. It was the version of my default emacs, which was not using org9. I appreciate your help.
