### ISSUE TITLE
[orgmode] Problem in loading emacs-htmlize

### ISSUE THREAD

**Issue by hilman-dayo** [getnikola/plugins#287]
I am using [Spacemaces](https://github.com/syl20bnr/spacemacs) (a distribution of emacs) with org-mode 9.1.14. Previously, Nikola with org-mode (I believe it was org-mode v8.x) worked just fine, but recently, I got error as in below. This error prevent my latest org post to be converted into proper html. I think this problem starts to occurred after I updated my Spacemacs in which the org-mode is updated into version 9.x.

    (cv) owlan058088:defpython hilman_dayo$ nikola auto -b
    Scanning posts..........done!
    .  render_posts:cache/posts/dari-zero-ke-pythonista-dzp-satu-permulaan.html
    Loading /Users/hilman_dayo/Documents/webby/defpython/plugins/orgmode/conf.el (source)...
    Created img-url link.
    Please install htmlize from https://github.com/hniksic/emacs-htmlize
    TaskError - taskid:render_posts:cache/posts/dari-zero-ke-pythonista-dzp-satu-permulaan.html
    PythonAction Error
    Traceback (most recent call last):
      File "/Users/hilman_dayo/Documents/webby/defpython/plugins/orgmode/orgmode.py", line 74, in compile
        subprocess.check_call(command)
      File "/Users/hilman_dayo/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['emacs', '--batch', '-l', '/Users/hilman_dayo/Documents/webby/defpython/plugins/orgmode/init.el', '--eval', '(nikola-html-export "/Users/hilman_dayo/Documents/webby/defpython/posts/dari-zero-ke-pythonista-dzp-satu-permulaan.org" "/Users/hilman_dayo/Documents/webby/defpython/cache/posts/dari-zero-ke-pythonista-dzp-satu-permulaan.html")']' returned non-zero exit status 255.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/doit/action.py", line 424, in execute
        returned_value = self.py_callable(*self.args, **kwargs)
      File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/nikola/post.py", line 578, in compile
        lang)
      File "/Users/hilman_dayo/Documents/webby/defpython/plugins/orgmode/orgmode.py", line 94, in compile
        source, e.returncode))
    Exception: Cannot compile posts/dari-zero-ke-pythonista-dzp-satu-permulaan.org -- bad org-mode configuration (return code 255)

As you can see, it say `Please install htmlize from https://github.com/hniksic/emacs-htmlize`. However, the `init.el` file already load the package as like below:

    (require 'package)
    (setq package-load-list '((htmlize t)))
    (package-initialize)

    (require 'org)
    (require 'ox-html)

Plus, within the Spacemacs, I already assured that `htmlize` is installed inside the computer. Below is what I got from running `lazy-helm/describe-package` to describe the `htmlize` package 

    htmlize is a dependency package.

    Status: Installed in ‘htmlize-20180412.1944/’ (unsigned).
    Version: 20180412.1944
    Commit: 315a8f23cfd3e87642ff9e30ae3300c7a84244d5
    Summary: Convert buffer text and decorations to HTML.
    Required by: org-ref-20180820.1428, impatient-mode-20180901.2307
    Keywords: hypermedia extensions 
    Other versions: 20180412.1944 (melpa).

Any help is really appreciated.

**Comment by hilman-dayo** [comment]
Ok, I figured out the problem (kinda).

So, in a file named `temp.el`, I wrote this:

    (prin1 load-path)

Then, I run this:

    emacs --batch -l temp.el

I got this output:

    ("/Library/Application Support/Emacs/26.1/site-lisp"
    "/Library/Application Support/Emacs/site-lisp"
    "/Applications/Emacs.app/Contents/Resources/site-lisp"
    "/Applications/Emacs.app/Contents/Resources/lisp"
    "/Applications/Emacs.app/Contents/Resources/lisp/vc"
    "/Applications/Emacs.app/Contents/Resources/lisp/url"
    "/Applications/Emacs.app/Contents/Resources/lisp/textmodes"
    "/Applications/Emacs.app/Contents/Resources/lisp/progmodes"
    "/Applications/Emacs.app/Contents/Resources/lisp/play"
    "/Applications/Emacs.app/Contents/Resources/lisp/org"
    "/Applications/Emacs.app/Contents/Resources/lisp/nxml"
    "/Applications/Emacs.app/Contents/Resources/lisp/net"
    "/Applications/Emacs.app/Contents/Resources/lisp/mh-e"
    "/Applications/Emacs.app/Contents/Resources/lisp/mail"
    "/Applications/Emacs.app/Contents/Resources/lisp/leim"
    "/Applications/Emacs.app/Contents/Resources/lisp/language"
    "/Applications/Emacs.app/Contents/Resources/lisp/international"
    "/Applications/Emacs.app/Contents/Resources/lisp/image"
    "/Applications/Emacs.app/Contents/Resources/lisp/gnus"
    "/Applications/Emacs.app/Contents/Resources/lisp/eshell"
    "/Applications/Emacs.app/Contents/Resources/lisp/erc"
    "/Applications/Emacs.app/Contents/Resources/lisp/emulation"
    "/Applications/Emacs.app/Contents/Resources/lisp/emacs-lisp"
    "/Applications/Emacs.app/Contents/Resources/lisp/cedet"
    "/Applications/Emacs.app/Contents/Resources/lisp/calendar"
    "/Applications/Emacs.app/Contents/Resources/lisp/calc"
    "/Applications/Emacs.app/Contents/Resources/lisp/obsolete")

As you can see, it the path doesn't contain any `~/.emacs.d/*`, making the program not being able to load the `htmlize` package. So, I need to add

    (add-to-list 'load-path "~/.emacs.d/elpa/26.1/develop/htmlize-20180412.1944")
    (require 'htmlize)

to the `init.py` file of the orgmode plugin. This is just a quick fix I did. I guess maybe this problem has something to do with how the new emacs 26 works?

**Comment by punchagan** [comment]
This is the intended behavior of how the Nikola plugin is setup. It uses a custom `init.el` at startup, and doesn't use the Emacs default init file. This is done so that we avoid slow Emacs start-ups and confusing configurations.
