### ISSUE TITLE
Problem Embedding iframe

### ISSUE THREAD

**Issue by ianbarton** [getnikola/plugins#291]
I am trying to embed an iframe which contains an Amazon Affiliate link.

`#+HTML: <iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=GB&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=ianbarton-21&language=en_GB&marketplace=amazon&region=GB&placement=B013YMS8QS&asins=B013YMS8QS&linkId=d5f7a077f2f0f6772480cc30e6ed364d&show_border=false&link_opens_in_new_window=false"></iframe>`

This exports, but the iframe tags get stripped out.

Page source from browser:
`<a href="http://www.amazon.co.uk/s/?ie=UTF8&amp;keywords=thermos+ultimate+flask&amp;tag=googhydr-21&amp;index=aps&amp;hvadid=87479041689&amp;hvpos=1t1&amp;hvexid=&amp;hvnetw=g&amp;hvrand=17120847490637546718&amp;hvpone=&amp;hvptwo=&amp;hvqmt=b&amp;hvdev=c&amp;ref=pd_sl_8jpzbd08h0_b">http://www.amazon.co.uk/s/?ie=UTF8&amp;keywords=thermos+ultimate+flask&amp;tag=googhydr-21&amp;index=aps&amp;hvadid=87479041689&amp;hvpos=1t1&amp;hvexid=&amp;hvnetw=g&amp;hvrand=17120847490637546718&amp;hvpone=&amp;hvptwo=&amp;hvqmt=b&amp;hvdev=c&amp;ref=pd_sl_8jpzbd08h0_b</a>`

**Comment by Kwpolska** [comment]
This seems to be a thing with orgmode itself (works with other formats in Nikola). Please try reproducing with orgmode’s export facilities, and if you can reproduce, report the bug to the org-mode team.

**Comment by punchagan** [comment]
Sounds like the right diagnosis. :+1:

**Comment by ianbarton** [comment]
After some experimentation the following exports correctly:
`#+begin_export html
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=GB&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=ianbarton-21&language=en_GB&marketplace=amazon&region=GB&placement=B013YMS8QS&asins=B013YMS8QS&linkId=d5f7a077f2f0f6772480cc30e6ed364d&show_border=false&link_opens_in_new_window=false"></iframe>
#+end_export
`

Generated page source:

`

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-eu.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&amp;OneJS=1&amp;Operation=GetAdHtml&amp;MarketPlace=GB&amp;source=ss&amp;ref=as_ss_li_til&amp;ad_type=product_link&amp;tracking_id=ianbarton-21&amp;language=en_GB&amp;marketplace=amazon&amp;region=GB&amp;placement=B013YMS8QS&amp;asins=B013YMS8QS&amp;linkId=d5f7a077f2f0f6772480cc30e6ed364d&amp;show_border=false&amp;link_opens_in_new_window=false"></iframe>
--
`

However, the iframe isn't visible on the page. That's a theme problem, not a Nikola one:)

**Comment by punchagan** [comment]
> However, the iframe isn't visible on the page. That's a theme problem, not a Nikola one:)

Thanks for clarifying!
