### ISSUE TITLE
[orgmode] possibility to write Rst within org files?

### ISSUE THREAD

**Issue by ashfaqfarooqui** [getnikola/plugins#292]
I want to embed rst features within my org document, by using other plugins available here.

For example, I want to use the publication_list plugin or the book_figure plugin. Both of which are in rst format. 
Can I use these plugins within my org-mode files? If so how?

**Comment by Kwpolska** [comment]
No, you can’t. You will need to use reST. If the plugins you want to use are available as shortcodes as well, then you could use other formats, but IIRC, the orgmode plugin does not support shortcodes.
