### ISSUE TITLE
[sphinx_roles] abbr eplanation not taken into account

### ISSUE THREAD

**Issue by matclab** [getnikola/plugins#294]
Using ```:abbr:`WTF (Want To Fly)` ``` get translated into `<abbr>WTF</abbr>` with sphinx_roles plugin 0.4 on Nikola 8.0.1 with python 3.7.1 on Arch Linux;

Putting some debugging info, it looks like `visit_abbreviation` is never called.

**Comment by ralsina** [comment]
Ok, seems like I should actually remove this soonish.

According to sphinx source code, this is deprecated because docutils has added abbreviation support.
And according to the docutils code, it's not working:

```
    def visit_abbreviation(self, node):
        # @@@ implementation incomplete ("title" attribute)
```

I will take a shot at fixing it but I have no idea why the visitor is not working.

**Comment by matclab** [comment]
@ralsina, by chance did you manage to get some result on this one ?

**Comment by matclab** [comment]
after some investigation, it looks like `add_node` change the visitor of `docutils.writers.html5_polyglot.HTMLTranslator` whereas the `abbr_visitor` used is the one from `docutils.writers.html4css1.HTMLTranslator`.

**Comment by matclab** [comment]
Replacing `html5_polyglot` with `html4css1` in `nikola/plugins/compile/rest/__init__.py` works. Shall I propose a PR or could you elaborate on the difference between the two writers and why one is selected preferably to another ?

**Comment by ralsina** [comment]
Honestly, I have no idea what the difference is :-(

**Comment by matclab** [comment]
The difference is documented here : http://docutils.sourceforge.net/docs/user/html.html
Replacing `writer_name='html'` with `writer_name='html5_polyglot'` in `nikola/plugins/compile/rest/__init__.py:rst2html` parameter initialization does the job.

**Comment by matclab** [comment]
But then the math rendering is broken… Still investigating.

**Comment by matclab** [comment]
The math problem is unrelated… It was a glitch in the network connection.

**Comment by ralsina** [comment]
I suppose if the tests pass it's ok.
