### ISSUE TITLE
[gallery_directive] gallery_directive.tmpl location?

### ISSUE THREAD

**Issue by shdobxr** [getnikola/plugins#317]
Good Day, looking through the manual I don't see where I place my gallery_directive.tmpl sample to begin customization. My initial thought is that it would be placed within the `/home/user/<nikola_site>/themes/<nameoftheme>/templates` folder.

However upon doing so... no change on the rendering of the gallery. Also the documentation is quite clear about embedding images. But I felt that there could be more polish to the gallery insertion. And found the gallery_directive plugin, which seems much easier to use.

Any assistance here would be great.

**Comment by Kwpolska** [comment]
Works for me. Are you sure your theme is active in `conf.py`? I can see changes in the rendered output with this:

```console
$ nikola init -qd n; cd n
$ nikola plugin -i gallery_directive
$ nikola theme -n test
$ echo 'THEME="test"' >> conf.py
$ nikola theme -c gallery_directive.tmpl
[2019-10-26T10:06:15Z] INFO: theme: Created directory themes/test/templates
[2019-10-26T10:06:15Z] INFO: theme: Copied template from …/n/plugins/gallery_directive/templates/mako/gallery_directive.tmpl to themes/test/templates/gallery_directive.tmpl
$ vim themes/test/templates/gallery_directive.tmpl posts/1.rst
$ nikola build
```

**Comment by shdobxr** [comment]
Thanks for the input @Kwpolska. I didn't see in the documentation the need for the following command
`nikola theme -c gallery_directive.tmpl` I performed this, but for some reason my gallery insists on splitting 2 photos into two rows. 
[My Blog](https://shdobxr.github.io/s2k_project/)

**Comment by Kwpolska** [comment]
The command is not necessary if you copy the file manually.

I cloned your site, modified `themes/zen/gallery_directive.tmpl` and the change was reflected. The template file you have is compatible with Bootstrap 3+, and the Zen themes are not based on Bootstrap. You will need to write CSS rules that do what you want yourself.
