### ISSUE TITLE
[postcast] No episodes in RSS

### ISSUE THREAD

**Issue by larsbjorndal** [getnikola/plugins#318]
No information from the associated .rst files are inserted into the .xml file from Postcast plugin. 
In the config, I have.

POSTCAST_PATH = 'casts'
POSTCASTS = ['visioneers_cast']

POSTCAST_CATEGORY = {
    'visioneers_cast': 'cast_episode',
}

# Filter posts to be included in a feed with a list of tags. The # default is all posts. Specifying tags for the '' feed will result in # all feeds being filtered by those tags.
#POSTCAST_TAGS = {
#    'visioneers_cast': ['podcast-episode'],
#}

[...]

POSTCAST_ITUNES_EXPLICIT = {
    'False': False,
}

In one of the .rst files in pages, I have:

.. title: Episode 2
.. slug: episode002
.. date: 2019-09-14 20:52:34 UTC+02:00
.. tags: 
.. category: cast_episode
.. link: 
.. description: 
.. type: text
.. author: the name
.. enclosure: /podcast/episode_002.mp3
.. itunes_image: /podcast/Thumbnail_PODCAST-VisioneersNorway_50.png
.. itunes_duration: 30:08

I'm not sure what I'm doing wrong. The source is here:

<http://lamasti.net/filer/visioneers-source.tar.gz>

Hope you can give som hint.

Thanks in advance,

**Comment by Kwpolska** [comment]
@anderbubble, can you take a look?

**Comment by larsbjorndal** [comment]
I fiddled more and found that .rst files under pages are not included, but only .rst files under posts. In addition, I found that the enclosed .mp3 files have to be stored under files/posts/<name of the rst file>/. Could you please change the behavior so that both pages and posts are generated, and also so that the path for the .mp3 file could be e.g. /podcast/episode.mp3? Hope this makes sense.

Thanks in advance

**Comment by ralsina** [comment]
Yes, feeds only include posts, not pages. Pages not necessarily have a
date, so it makes no sense to have a RSS feed of pages.

**Comment by larsbjorndal** [comment]
Ok, thank you. I suppose it's not advisable to have more than one Post section in the conf.py file, pointing to different locations?

**Comment by Kwpolska** [comment]
It’s allowed, but note that your podcast posts will appear in the main indexes/feeeds as well.
