### ISSUE TITLE
[orgmode]

### ISSUE THREAD

**Issue by dalanicolai** [getnikola/plugins#329]
Please WARN in the "Suggested Configuration" (of the Nikola plugin website) section that the trailing comma in the COMPILERS list is essential.

The syntax of the COMPILERS section in the conf.py file is slightly different from your example. Therefore I did not copy paste the code, and forgot to place the comma. I spent about one hour hunting the cause for nikola not recognizing the org compiler...

**Comment by Kwpolska** [comment]
I changed all the examples to use lists, because we convert it to lists later anyways.
