### ISSUE TITLE
[orgmode] Enable to export inline images with file scheme

### ISSUE THREAD

**Issue by shishimaru** [getnikola/plugins#334]
[ Background ]
Currently we need to refer inline images with dedicated scheme img-url.
However, during editing with orgmode, Emacs orgmode can't recogine the scheme and it is inconvenient because they are invisible on Emacs.

[ Task ]
Support file scheme supported by Emacs orgmode.

**Comment by Kwpolska** [comment]
Are you willing to provide a patch? (Nikola is not going to support `/foo.png` or `foo.png` in the way orgmode expects; if you want to make a `file://` scheme, and it can be used with relative URLs, we can accept that patch.)

**Comment by shishimaru** [comment]
@Kwpolska 
Yes, I have the patch. Could I push my working branch ?

**Comment by Kwpolska** [comment]
@shishimaru Make a pull request.

**Comment by shishimaru** [comment]
@Kwpolska 
I made the pull request. Could you check ?
