### ISSUE TITLE
[latex]

### ISSUE THREAD

**Issue by fritz-heinrichmeyer** [getnikola/plugins#341]
Nikola version: v8.0.4
plugins: latex
LATEX_FORMULA_RENDERER = "latex_formula_mathjax"
ERROR: Nikola: KeyError: 'math_thm_name'
pdflatex diskrete_faltung1.tex:
Output written on diskrete_faltung1.pdf (no error)

**Comment by felixfontein** [comment]
Have you read (and implemented) [this section](https://github.com/getnikola/plugins/tree/master/v7/latex#required-translations) in your theme?

**Comment by fritz-heinrichmeyer** [comment]
Have you read (and implemented) this section in your theme?
yes, I have

**Comment by fritz-heinrichmeyer** [comment]
No, I have not,(my fault,sorry)

**Comment by fritz-heinrichmeyer** [comment]
it work, Thanks.

**Comment by felixfontein** [comment]
I'm glad to hear! :)
