### ISSUE TITLE
[hierarchical_pages] nikola new_page doesn't work with hierarchical pages

### ISSUE THREAD

**Issue by danshapero** [getnikola/plugins#350]
I'm using the suggested configuration for the hierarchical pages plugin, where `PAGES = ()` and instead that configuration is moved into a `HIERARCHICAL_PAGES` variable. When I try to run `nikola new_page`, I get the following error message:

    [2020-09-09T20:51:24Z] ERROR: new_page: Can't find a way, using your configuration, to create a page in format rest. You may want to tweak COMPILERS or PAGES in conf.py

I'm guessing this is because I've removed everything from `PAGES`, but when I restore to what it was before I get a bunch of errors because it collides with `HIERARCHICAL_PAGES`. I can always make a new page with the right metadata by hand, but it's more convenient to have the command for it.

**Comment by ralsina** [comment]
Indeed new_pages doesn't know anything about that plugin, we should add a
note in its README

OTOH, new_page doesn't really do much, you could just create the pages
manually.

**Comment by ralsina** [comment]
On a footnote, I don't understand at all what that plugin does from reading
the README

**Comment by felixfontein** [comment]
@ralsina it not only allows to change the filename depending on the language, but also the path leading to that file.
