### ISSUE TITLE
[orgmode]

### ISSUE THREAD

**Issue by ndvanforeest** [getnikola/plugins#354]
Hi,

I suppose it must be very simple, but I can't find how to get links working in the orgmode plugin. For instance, 

[[link://slug/index][home]] 

seems most reasonable to me, but any variant I try doesn't work. Any idea?

**Comment by Kwpolska** [comment]
How does it fail? If you replace `link://` with `http://`, does it work?

**Comment by ndvanforeest** [comment]
Thanks for your answer. Your suggestion works when used  for "real" addresses, like HTTP://google.com, but not for links to pages within my site. To be safe, I tested this, with the following string in my org file:

[[http://pages/Bio]]

and it expands to this in the HTML file:

<p>
<a href="http://pages/Bio">http://pages/Bio</a>
</p>

This does not give a working link in my site, as expected.  Now leaving out the HTTP:// in the org file, like so

[[../pages/Bio]]

gives as HTML:

<p>
<img src="pages/Bio" alt="nil"></p>

So, for some reason links to pages in the org file get converted to an image. 

Just to be sure, I let org mode convert my org file to HTML, but then things work right. So, something in the orgmode plugin for nikola goes wrong, but I have no clue what that can be. 

It is not a big deal in the sense that I can always hard code the links of my side on github pages into the org files, but it annoys me that such a basic thing as cross linking between pages in one site does not seem to work..

**Comment by ralsina** [comment]
Using a link like "../pages/Bio" is probably not always going to work
correctly, remember that the same content may appear in more than once
place in your site.

Try "/pages/Bio" instead (or whatever is appropriate)

**Comment by ndvanforeest** [comment]
Thanks. I tried all such variations, using the slug, with //, just one /, no /, anything that I could imagine.  I am now at the point that I ll write a simple script to convert the http string to my GitHub pages site equivalent. It’s not elegant, pretty dumb in fact, but that I can get to work for sure.

**Comment by Kwpolska** [comment]
It should never be necessary to run a shell script to fix a Nikola site. Perhaps you need a different syntax to convince orgmode to output a link. Replacing link:// happens at a very late stage of the build, all you need to have it in `<a href="">`.

**Comment by Kwpolska** [comment]
Based on [this](https://kitchingroup.cheme.cmu.edu/blog/2016/11/04/New-link-features-in-org-9/) (and the [official docs example](https://orgmode.org/manual/Adding-Hyperlink-Types.html) seems to be broken, which is just A-W-E-S-O-M-E…), I wrote this

```el
(org-link-set-parameters
 "link"
 :export (lambda (path desc backend)
           (cond
            ((eq 'html backend)
             (format "<a href=\"link:%s\">%s</a>"
                     path (or desc path)))))
)
```

@ndvanforeest, can you test with your site (in `init.el`, requires `rm -rf cache` to test)? If it works, I guess we could add it to the file.

**Comment by ndvanforeest** [comment]
It works! So as to prevent any misunderstanding, I copied your elisp
expression into the init.el of the org mode plugin for nikola (so not into
my general init.el). Then I use the following string in my org file to
refer to the file pages/bio.org (i.e, the html generated version of it):
[[link:/bio][boi]]

Many thanks. Would it be an idea to update the docs of the orgmode plugin?
I am a recent org mode renegade (after using nuweb, noweb, pweave... for
the past 20 years), and to me it comes as a surprise that nikola seems to
need the keywords "link"; the orgmode documentation uses keywords like
"file:" and so on, but not "link:".

**Comment by Kwpolska** [comment]
`link://` is Nikola-specific. Many formats don’t care about the scheme and will just generate a link, no matter if it’s `https`, `gopher`, `link`, or `qwerty`. I created PR #356 with the fix.
