### ISSUE TITLE
Change to sass does not trigger nikola auto rebuild

### ISSUE THREAD

**Issue by wohali** [getnikola/plugins#379]
This seems to be a regression of https://github.com/getnikola/nikola/issues/966 .

With the `sass` plugin installed, changing files under the `sass/` subdirectory does not trigger a rebuild when `nikola auto` is running.

Manually running `nikola build` detects the change and rebuilds the CSS from the SASS sources.

**Comment by Kwpolska** [comment]
The `sass` and `less` plugins should add the source folder to `site.registered_auto_watched_folders` (in `set_site`) to work with `nikola auto`. Want to make a PR fixing this in both plugins?

**Comment by wohali** [comment]
@Kwpolska Sure, looks easy. Give me a bit.
