### ISSUE TITLE
[orgmode]

### ISSUE THREAD

**Issue by shilet** [getnikola/plugins#393]
The code to export images does not include html attrs. For instance, 

#+ATTR_HTML: :width 100px; 
[[/images/picture.png]]

expands to 

<p><img src="../images/picture.png" alt="nil"></p>

If I remove the part of the init.el of the orgmode plugin that deals with the images I get this:

<p><img src="file:///images/jorden_tata.png" alt="jorden_tata.png" width="100px;"></p>

Specifically, to get this, I commented out in init.el: 
 ; (org-add-link-type "file" nil 'org-file-link-img-url-export)

**Comment by laodzu** [comment]
So I just checked this on my local installation with Nikola v8.2.3 and orgmode plugin at version 0.3.

Here is the source:

```
#+ATTR_HTML:`` :style text-align:center
#+BEGIN_imageblock
#+ATTR_HTML: :title Big lock :align middle :width 150
[[../../images/nikola-50px-grey.png]]
#+END_imageblock
```

and this is in the output:

```
<div id="orgc443038" class="figure">
<p><img src="[../../images/nikola-50px-grey.png](view-source:http://127.0.0.1:8000/images/nikola-50px-grey.png)" alt="nikola-50px-grey.png" title="Big lock" align="middle" width="150"></p>
</div>
```

So the title, align and width attributes were passed correctly to html.

So I think this issue can be closed, or what do you think?
