### ISSUE TITLE
[localsearch] Deprecate localsearch

### ISSUE THREAD

**Issue by htgoebel** [getnikola/plugins#417]
I suggest deprecating the "localsearch" plugin, as it is based on Tipue which seams to be vanished.

- In the docs of the"localsearch" plugin the link to http://www.tipue.com/search/ which now belongs to a music bands' website.
- [Pelican plugin tipue-search](https://github.com/pelican-plugins/tipue-search) points to https://web.archive.org/web/20200703134724/https://tipue.com/search/ (and recommends using another plugin)
- [jekyll-tipue-search](https://github.com/jekylltools/jekyll-tipue-search) points to https://github.com/Tipue/Tipue-Search which is not valid either.
- [jqueryscript.net/](https://www.jqueryscript.net/other/jQuery-Site-Search-Engine-Plugin-Tipue-Search.html) also links to the outdated site.
- Same at https://pasdoc.github.io/UseTipueSearchOption

**Comment by Kwpolska** [comment]
The plugin works, there is no alternative Nikola plugin, so I don't see the point in deprecating it. Feel free to contribute an alternative plugin, then we can decide what to do with Tipue.

**Comment by ralsina** [comment]
I vaguely recall doing a similar one based on Lunr search?

Can't find any trace of it tho.
