### ISSUE TITLE
[spell_check] Third-party dependency does not exist

### ISSUE THREAD

**Issue by roxybanker** [getnikola/plugins#427]
I'm getting this error:
![image](https://github.com/getnikola/plugins/assets/130113557/270e75e0-c168-4957-8191-706e6cc6e32f)

But the link for abisource is not available.
![image](https://github.com/getnikola/plugins/assets/130113557/85ca9495-5c62-4472-b442-b58cbe225895)

**Comment by Kwpolska** [comment]
I updated the URL to https://abiword.github.io/enchant/ .
