### ISSUE TITLE
gallery_directive puts garbage in the output

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/plugins#71]
The gallery_directive plugin puts too much cruft in the output.  It should be rewritten so that only relevant bits are included.  You can only see a duplicated footer, but the header and all the links/scripts/whatnot are also there…

We might need to refactor gallery templates — for example, create a special gallery_content.tmpl, and make `gallery.tmpl` just inherit from base and throw in `gallery_content.tmpl`.

//cc @ralsina

**Comment by Kwpolska** [comment]
@ralsina: bump http://t.co/7FuloPylH5

**Comment by ralsina** [comment]
Ack.

**Comment by ralsina** [comment]
I *think* this is not happening anymore.
