### ISSUE TITLE
plugin vcs issues

### ISSUE THREAD

**Issue by duck** [getnikola/plugins#88]
Just installed the vcs module following the instructions.

nikola installed via pip.

Arch Linux

    don@dragon:~/tmp/www.duckland.org> uname -a
    Linux dragon.home.duckland.org 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux
    don@dragon:~/tmp/www.duckland.org> nikola version
    Nikola v7.5.0

    don@dragon:~/tmp/www.duckland.org> nikola plugin --list-installed
    auto at /usr/lib/python3.4/site-packages/nikola/plugins/command/auto.py
    bootswatch_theme at /usr/lib/python3.4/site-packages/nikola/plugins/command/bootswatch_theme.py
    check at /usr/lib/python3.4/site-packages/nikola/plugins/command/check.py
    console at /usr/lib/python3.4/site-packages/nikola/plugins/command/console.py
    copy_assets at /usr/lib/python3.4/site-packages/nikola/plugins/task/copy_assets.py
    copy_files at /usr/lib/python3.4/site-packages/nikola/plugins/task/copy_files.py
    create_bundles at /usr/lib/python3.4/site-packages/nikola/plugins/task/bundles.py
    deploy at /usr/lib/python3.4/site-packages/nikola/plugins/command/deploy.py
    generate_rss at /usr/lib/python3.4/site-packages/nikola/plugins/task/rss.py
    github_deploy at /usr/lib/python3.4/site-packages/nikola/plugins/command/github_deploy.py
    gzip at /usr/lib/python3.4/site-packages/nikola/plugins/task/gzip.py
    html at /usr/lib/python3.4/site-packages/nikola/plugins/compile/html.py
    import_feed at /home/don/tmp/www.duckland.org/plugins/import_feed/import_feed.py
    import_wordpress at /usr/lib/python3.4/site-packages/nikola/plugins/command/import_wordpress.py
    init at /usr/lib/python3.4/site-packages/nikola/plugins/command/init.py
    install_theme at /usr/lib/python3.4/site-packages/nikola/plugins/command/install_theme.py
    ipynb at /usr/lib/python3.4/site-packages/nikola/plugins/compile/ipynb/
    jinja at /usr/lib/python3.4/site-packages/nikola/plugins/template/jinja.py
    less at /home/don/tmp/www.duckland.org/plugins/less/less.py
    mako at /usr/lib/python3.4/site-packages/nikola/plugins/template/mako.py
    markdown at /usr/lib/python3.4/site-packages/nikola/plugins/compile/markdown/
    mdx_gist at /usr/lib/python3.4/site-packages/nikola/plugins/compile/markdown/mdx_gist.py
    mdx_nikola at /usr/lib/python3.4/site-packages/nikola/plugins/compile/markdown/mdx_nikola.py
    mdx_podcast at /usr/lib/python3.4/site-packages/nikola/plugins/compile/markdown/mdx_podcast.py
    new_page at /usr/lib/python3.4/site-packages/nikola/plugins/command/new_page.py
    new_post at /usr/lib/python3.4/site-packages/nikola/plugins/command/new_post.py
    orphans at /usr/lib/python3.4/site-packages/nikola/plugins/command/orphans.py
    pandoc at /usr/lib/python3.4/site-packages/nikola/plugins/compile/pandoc.py
    php at /usr/lib/python3.4/site-packages/nikola/plugins/compile/php.py
    plugin at /usr/lib/python3.4/site-packages/nikola/plugins/command/plugin.py
    redirect at /usr/lib/python3.4/site-packages/nikola/plugins/task/redirect.py
    render_archive at /usr/lib/python3.4/site-packages/nikola/plugins/task/archive.py
    render_galleries at /usr/lib/python3.4/site-packages/nikola/plugins/task/galleries.py
    render_indexes at /usr/lib/python3.4/site-packages/nikola/plugins/task/indexes.py
    render_listings at /usr/lib/python3.4/site-packages/nikola/plugins/task/listings.py
    render_pages at /usr/lib/python3.4/site-packages/nikola/plugins/task/pages.py
    render_posts at /usr/lib/python3.4/site-packages/nikola/plugins/task/posts.py
    render_sources at /usr/lib/python3.4/site-packages/nikola/plugins/task/sources.py
    render_tags at /usr/lib/python3.4/site-packages/nikola/plugins/task/tags.py
    rest at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/
    rest_chart at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/chart.py
    rest_doc at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/doc.py
    rest_gist at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/gist.py
    rest_listing at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/listing.py
    rest_media at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/media.py
    rest_post_list at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/post_list.py
    rest_slides at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/slides.py
    rest_soundcloud at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/soundcloud.py
    rest_thumbnail at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/thumbnail.py
    rest_vimeo at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/vimeo.py
    rest_youtube at /usr/lib/python3.4/site-packages/nikola/plugins/compile/rest/youtube.py
    robots at /usr/lib/python3.4/site-packages/nikola/plugins/task/robots.py
    rst2html at /usr/lib/python3.4/site-packages/nikola/plugins/command/rst2html/
    sass at /home/don/tmp/www.duckland.org/plugins/sass/sass.py
    scale_images at /usr/lib/python3.4/site-packages/nikola/plugins/task/scale_images.py
    scan_posts at /usr/lib/python3.4/site-packages/nikola/plugins/misc/scan_posts.py
    serve at /usr/lib/python3.4/site-packages/nikola/plugins/command/serve.py
    sitemap at /usr/lib/python3.4/site-packages/nikola/plugins/task/sitemap/
    smtp at /usr/lib/python3.4/site-packages/nikola/plugins/loghandler/smtp.py
    status at /usr/lib/python3.4/site-packages/nikola/plugins/command/status.py
    stderr at /usr/lib/python3.4/site-packages/nikola/plugins/loghandler/stderr.py
    upgrade_metadata at /home/don/tmp/www.duckland.org/plugins/upgrade_metadata/upgrade_metadata.py
    vcs at /home/don/tmp/www.duckland.org/plugins/vcs/vcs.py
    version at /usr/lib/python3.4/site-packages/nikola/plugins/command/version.py

The error is throws is this:

    don@dragon:~/tmp/www.duckland.org> nikola vcs
    Scanning posts......done!
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/doit/doit_cmd.py", line 165, in run
        return command.parse_execute(args)
      File "/usr/lib/python3.4/site-packages/doit/cmd_base.py", line 122, in parse_execute
        return self.execute(params, args)
      File "/usr/lib/python3.4/site-packages/nikola/plugin_categories.py", line 124, in execute
        self._execute(options, args)
      File "/home/don/tmp/www.duckland.org/plugins/vcs/vcs.py", line 66, in _execute
        for s in wd.status():
      File "/usr/lib/python3.4/site-packages/anyvc/common/workdir.py", line 155, in parse_status_items
        for item in items:
      File "/usr/lib/python3.4/site-packages/anyvc/git/workdir.py", line 84, in status_impl
        wd = ls_files("tdmo")
      File "/usr/lib/python3.4/site-packages/anyvc/git/workdir.py", line 79, in ls_files
        state, name = item.split(" ", 1)
    TypeError: 'str' does not support the buffer interface
    

My python-fu is not very good, but I am willing to test any changes...

Thanks!

d

**Comment by ralsina** [comment]
I did not try it at all with python3, I'll do so later today.

**Comment by ralsina** [comment]
Looks like anyvc (which this plugin uses to interact with git, etc), sucks at python3. So, can't do much about it.
