### ISSUE TITLE
Site not showing any plugin information

### ISSUE THREAD

**Issue by notfoss** [getnikola/plugins#92]
On plugins.getnikola.com, I am able to see the plugin list on the left side of the web page, but I cannot see any information for the selected plugin.

<a href='http://postimg.org/image/m287mibal/' target='_blank'><img src='http://s14.postimg.org/m287mibal/2015_07_09_154501.jpg' border='0' alt="2015 07 09 154501" /></a>

**Comment by Kwpolska** [comment]
@felixfontein broke it with a misnamed `.plugin` file.

Need to get working on #90 FAST.

**Comment by ffdybuster** [comment]
Sorry for breaking it!
